name: Release

on:
    # Allows you to run this workflow manually from the Actions tab or through HTTP API
    workflow_dispatch:

    push:
        tags:
            - "v*.*.*" # Trigger only on version tags

jobs:
    build:
        strategy:
            matrix:
                # os: [ubuntu-latest, macos-latest, windows-latest]
                # arch: [x64, ia32]
                include:
                    - os: ubuntu-latest
                      arch: x64
                    # - os: ubuntu-latest # BUG: This one doesn't work.
                    #   arch: ia32
                    - os: ubuntu-latest
                      arch: arm64
                    - os: ubuntu-latest
                      arch: armv7l
                    - os: macos-latest
                      arch: x64
                    # - os: macos-latest # BUG: This one doesn't work.
                    #   arch: ia32
                    - os: macos-latest
                      arch: arm64
                    # - os: macos-latest # BUG: This one doesn't work.
                    #   arch: armv7l
                    - os: windows-latest
                      arch: x64
                    - os: windows-latest
                      arch: ia32
                      node-version: 22.x
                    # - os: windows-11-arm # Disabled because Windows arm64 can run x64 apps.
                    #   arch: arm64
                    # - os: windows-latest # BUG: This one doesn't work.
                    #   arch: armv7l
        runs-on: ${{ matrix.os }}
        name: Build ${{ matrix.os }} (${{ matrix.arch }})
        permissions: write-all
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Setup Node.js
              uses: actions/setup-node@v6

            - name: Pull submodules
              run: git submodule update --init --recursive

            - name: Install dependencies
              run: npm install

            # - name: Make distributables
            #   run: npm run make -- --dry-run --arch="${{ matrix.arch }}"
            - name: Publish to GitHub Releases
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: npm run publish -- --arch="${{ matrix.arch }}"
